<?php 
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class ProdaneUlaznice {
	private $prodane_ulaznice_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'prodane_ulaznice_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'prodane_ulaznice_page_init' ) );
	}

	public function prodane_ulaznice_add_plugin_page() {
		add_menu_page(
			'Prodane ulaznice', // page_title
			'Prodane ulaznice', // menu_title
			'manage_options', // capability
			'prodane-ulaznice', // menu_slug
			array( $this, 'prodane_ulaznice_create_admin_page' ), // function
			'dashicons-admin-generic', // icon_url
			2 // position
		);
	}

	public function prodane_ulaznice_create_admin_page() {
		$this->prodane_ulaznice_options = get_option( 'prodane_ulaznice_option_name' ); ?>

		<div class="wrap">
			<h2>Prodane ulaznice</h2>
			<p></p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'prodane_ulaznice_option_group' );
					do_settings_sections( 'prodane-ulaznice-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function prodane_ulaznice_page_init() {
		register_setting(
			'prodane_ulaznice_option_group', // option_group
			'prodane_ulaznice_option_name', // option_name
			array( $this, 'prodane_ulaznice_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'prodane_ulaznice_setting_section', // id
			'Settings', // title
			array( $this, 'prodane_ulaznice_section_info' ), // callback
			'prodane-ulaznice-admin' // page
		);

		add_settings_field(
			'prodano_ulaznica_0', // id
			'Prodano ulaznica', // title
			array( $this, 'prodano_ulaznica_0_callback' ), // callback
			'prodane-ulaznice-admin', // page
			'prodane_ulaznice_setting_section' // section
		);

		add_settings_field(
			'prodano_student_1', // id
			'Prodano student', // title
			array( $this, 'prodano_student_1_callback' ), // callback
			'prodane-ulaznice-admin', // page
			'prodane_ulaznice_setting_section' // section
		);
	}

	public function prodane_ulaznice_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['prodano_ulaznica_0'] ) ) {
			$sanitary_values['prodano_ulaznica_0'] = sanitize_text_field( $input['prodano_ulaznica_0'] );
		}

		if ( isset( $input['prodano_student_1'] ) ) {
			$sanitary_values['prodano_student_1'] = sanitize_text_field( $input['prodano_student_1'] );
		}

		return $sanitary_values;
	}

	public function prodane_ulaznice_section_info() {
		
	}

	public function prodano_ulaznica_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="prodane_ulaznice_option_name[prodano_ulaznica_0]" id="prodano_ulaznica_0" value="%s">',
			isset( $this->prodane_ulaznice_options['prodano_ulaznica_0'] ) ? esc_attr( $this->prodane_ulaznice_options['prodano_ulaznica_0']) : ''
		);
	}

	public function prodano_student_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="prodane_ulaznice_option_name[prodano_student_1]" id="prodano_student_1" value="%s">',
			isset( $this->prodane_ulaznice_options['prodano_student_1'] ) ? esc_attr( $this->prodane_ulaznice_options['prodano_student_1']) : ''
		);
	}

}
if ( is_admin() )
	$prodane_ulaznice = new ProdaneUlaznice();

/* 
 * Retrieve this value with:
 * $prodane_ulaznice_options = get_option( 'prodane_ulaznice_option_name' ); // Array of All Options
 * $prodano_ulaznica_0 = $prodane_ulaznice_options['prodano_ulaznica_0']; // Prodano ulaznica
 * $prodano_student_1 = $prodane_ulaznice_options['prodano_student_1']; // Prodano student
 */
